# Generated by Django 4.2.5 on 2023-10-28 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Course',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('title', models.CharField(max_length=255)),
        #         ('description', models.TextField()),
        #         ('image', models.ImageField(default='static/Html.jpg', upload_to='course_images/')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='CourseContent',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('week_number', models.PositiveIntegerField()),
        #         ('theory', models.TextField(default='Theory')),
        #         ('chapter_number', models.PositiveIntegerField()),
        #         ('chapter_title', models.CharField(max_length=255)),
        #         ('video_id', models.CharField(default='X1quW4HxiCI7a6kC', max_length=11)),
        #         ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.course')),
        #     ],
        # ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=254)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        # migrations.CreateModel(
        #     name='Quiz',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('title', models.CharField(max_length=255)),
        #         ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.course')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='WeekProgress',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('week_number', models.PositiveIntegerField()),
        #         ('completed', models.BooleanField(default=False)),
        #         ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learn.course')),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='VideoProgress',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('progress', models.PositiveIntegerField(default=0)),
        #         ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.coursecontent')),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='QuizCompletion',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('completion_date', models.DateTimeField(auto_now_add=True)),
        #         ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.course')),
        #         ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.quiz')),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Question',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('text', models.CharField(max_length=255)),
        #         ('options', models.ManyToManyField(related_name='questions', to='learn.option')),
        #         ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.quiz')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Enrollment',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('enrolled_at', models.DateTimeField(auto_now_add=True)),
        #         ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.course')),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
    ]
